local SoundData = {["Military"] = {	"Burn1",
									"Burn2",
									"Burn3",
									"Burn4",
									"Burn5",
									"Burn6",
									"Burn7",
									"Burn8",
									"Burn9",
									"Burn10",
									"Drumhorn",
									"Ignite_Oil",
									"Ignite_Pitch",
									"LordDie_01",
									"RamHit_01",
									"RamHit_02",
									"RamHit_03",
									"SiegeRoll1",
									"SiegeRoll2",
									"SiegeRoll3",
									"SiegeRoll4"},
					["VoicesMentor"] = {"HAPPY_Silversmith",
										"INFO_NotEnoughSilver_rnd_01",
										"INFO_NotEnoughSilver_rnd_02",
										"JOIN_Silversmith",
										"LEAVE_Silversmith",
										"MAD_Silversmith",
										"MINE_MineEmptySilver",
										"MINE_MineRunningLowGold",
										"MINE_MineRunningLowSilver",
										"SAD_Silversmith"},
					["Stronghold"] = {	"Arch_Light_Pitch1",
										"Engineer_AtkS1",
										"Engineer_AtkS2",
										"Engineer_AtkS3",
										"Engineer_AtkS4",
										"Engineer_AtkW1",
										"Engineer_MRam",
										"Engineer_PourOil1",
										"Engineer_PourOil2",
										"Engineer_PourOil3",
										"Engineer_PourOil4",
										"Engineer_PourOil5",
										"Engineer_PourOil6",
										"Engineer_PourOil7",
										"Engineer_PourOil8",
										"Engineer_PourOil9",
										"Engineer_Ram1",
										"Engineer_SRam",
										"General_Gatehouse",
										"General_QuitGame",
										"General_Victory1",
										"General_Victory2",
										"General_Victory3",
										"General_Victory4",
										"General_Victory5",
										"Wf_Vict_01",
										"Wf_Vict_02",
										"Wf_Vict_03",
										"Wf_Vict_04"}
					}
for k, v in pairs(SoundData) do
	table.foreachi(v, function(_, _value)
		CUtil.AddSound(k .. "\\" .. _value)
	end)
end

